-- Migration: Create tickets table
-- Created: 2024-12-20
-- Description: Initialize tickets table for helpdesk ticket management

CREATE TABLE IF NOT EXISTS tickets (
    id VARCHAR(36) PRIMARY KEY,
    customer_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(100),
    description TEXT,
    cause TEXT,
    handling TEXT,
    open_time DATETIME NOT NULL,
    close_time DATETIME NULL,
    duration_raw_hours DECIMAL(10,2) DEFAULT 0,
    duration_formatted VARCHAR(50),
    close_handling TEXT,
    handling_duration_raw_hours DECIMAL(10,2) DEFAULT 0,
    handling_duration_formatted VARCHAR(50),
    classification VARCHAR(100),
    sub_classification VARCHAR(100),
    status VARCHAR(50) DEFAULT 'open',
    handling1 TEXT,
    close_handling1 TEXT,
    handling_duration1_raw_hours DECIMAL(10,2) DEFAULT 0,
    handling_duration1_formatted VARCHAR(50),
    handling2 TEXT,
    close_handling2 TEXT,
    handling_duration2_raw_hours DECIMAL(10,2) DEFAULT 0,
    handling_duration2_formatted VARCHAR(50),
    handling3 TEXT,
    close_handling3 TEXT,
    handling_duration3_raw_hours DECIMAL(10,2) DEFAULT 0,
    handling_duration3_formatted VARCHAR(50),
    handling4 TEXT,
    close_handling4 TEXT,
    handling_duration4_raw_hours DECIMAL(10,2) DEFAULT 0,
    handling_duration4_formatted VARCHAR(50),
    handling5 TEXT,
    close_handling5 TEXT,
    handling_duration5_raw_hours DECIMAL(10,2) DEFAULT 0,
    handling_duration5_formatted VARCHAR(50),
    open_by VARCHAR(255),
    cabang VARCHAR(100),
    upload_timestamp BIGINT NOT NULL,
    rep_class VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    INDEX idx_open_time (open_time),
    INDEX idx_name (name),
    INDEX idx_upload_timestamp (upload_timestamp),
    INDEX idx_cabang (cabang),
    INDEX idx_status (status),
    INDEX idx_category (category),
    INDEX idx_customer_id (customer_id),
    INDEX idx_rep_class (rep_class)
) ENGINE=InnoDB;